### ISSUE TITLE
Fetching results until there aren't any more

### ISSUE THREAD

**Issue by jochemstoel** [normanlol/bing-scraper#2]
Hi,

Thanks for this package, I am somewhat confused about the _pageCount_ parameter though.  Your readme says 
> pageCount is the number of pages the scraper pulls. This variable must be an Interger and defaults to 1.

but this doesn't seem to be accurate. I only get the results of one page in _response.results_ It does not concatenate multiple pages. If I use pageCount = 1, I just get different results than when I set pageCount = 10, not all of them.

How would I go about implementing this in a way that it keeps fetching the next result page until there aren't any more? Maybe something like a [function* generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*) that keeps yielding results until response.nextHref has no value? This seems like a reasonable approach to me because if there is no next page, we reached the end. I want to get all the results from all pages of a given query.

I understand that if there are a lot of results, this will query thousands of pages but in my use case my search queries are very specific so that is not an issue.

As the author of this package, what do you recommend?

**Comment by normanlol** [comment]
Hi! 

It only *doesn't* get 10 pages if the scraper fails to get the next page, or the page is empty.
I would recommend either using a VPN or actually making sure your query gets that many pages.

If you continue facing this issue, let me know!
