### ISSUE TITLE
Sidebar jQuery doesnt function correctly

### ISSUE THREAD

**Issue by luuuk** [normanlol/bing-scraper#3]
Hey Norman - I'm trying to use your package for a school project, but realized that the Sidebar jquery always results in null results even for a Bing search w a sidebar. Would love to see this one fixed!

**Comment by normanlol** [comment]
Hi! This currently only works for certian sidebars right now, apologies. If you can give me some query examples - I can attempt to add support for them!

**Comment by luuuk** [comment]
All good, I was able to fork the repo and play w the jQuery a bit to make it work for my needs. I'm very new to NPM so still learning all those mechanics. Appreciate the response!
